# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html##文档：https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/##来源：https://github.com/hexojs/hexo/

# Site   #网站
title   标题: Hexo
subtitle: ''
description   描述: ''
keywords:
author   作者: John Doe
language: en
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'##设置你的网站网址在这里。例如，如果你使用GitHub Page，设置url为‘https://username.github.io/project’
url: http://example.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory   #目录
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing   #写
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable   启用: true # Open external links in new tab
  field   场: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false   假
post_asset_folder: false   假
relative_link: false   假
future: true   真正的
syntax_highlighter: highlight.js
highlight:
  line_number: true   真正的
  auto_detect: false   假
  tab_replace: ''
  wrap: true   真正的
  hljs: false   假
prismjs:
  preprocess: true   真正的
  line_number: true   真正的
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)# per_page：每页显示的帖子。（0 =禁用分页）
# order_by: Posts order. (Order by date descending by default)# order_by：发布订单。（默认按日期降序排序）
index_generator:
  path   路径: ''
  per_page: 10
  order_by: -date

# Category & Tag   #类别&标签
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true   真正的

# Date / Time format#日期/时间格式
## Hexo uses Moment.js to parse and display dateHexo使用Moment.js解析和显示日期
## You can customize the date format as defined in##可以自定义日期格式
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'updated_option支持‘mtime’， ‘date’， ‘empty’
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: Fluid

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy   部署:
type   类型: git   类型:git
repo   回购: https://github.com/klshuaige7klshuaige7.github.io.git回购:https://github.com/klshuaige7klshuaige7.github.io.git
branch   分支: main   主要分支:
